sudo: required

services: 
  - docker

language: python

script: 
  - python -m pytest -v
  - echo "script is work"

after_success:
  - sh echo ".travis.yml alive at least"
  - sh ./.travis/deploy_dockerhub.sh
